[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "fcc-medical-data-visualizer"
version = "0.0.0"
[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
seaborn = "*"
